// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expenses.proxies;

public class Employee extends system.proxies.User
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Expenses.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullName("FullName"),
		Phone("Phone"),
		Email("Email"),
		Submitted("Submitted"),
		Approved("Approved"),
		UserRole("UserRole"),
		UserType("UserType"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Expenses.Employee"));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		super(context, employeeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Expenses.Employee", employeeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Expenses.Employee");
	}

	/**
	 * @deprecated Use 'Employee.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static expenses.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return expenses.proxies.Employee.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static expenses.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new expenses.proxies.Employee(context, mendixObject);
	}

	public static expenses.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return expenses.proxies.Employee.initialize(context, mendixObject);
	}

	public static java.util.List<expenses.proxies.Employee> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<expenses.proxies.Employee> result = new java.util.ArrayList<expenses.proxies.Employee>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Expenses.Employee" + xpathConstraint))
			result.add(expenses.proxies.Employee.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Submitted
	 */
	public final java.lang.String getSubmitted()
	{
		return getSubmitted(getContext());
	}

	/**
	 * @param context
	 * @return value of Submitted
	 */
	public final java.lang.String getSubmitted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Submitted.toString());
	}

	/**
	 * Set value of Submitted
	 * @param submitted
	 */
	public final void setSubmitted(java.lang.String submitted)
	{
		setSubmitted(getContext(), submitted);
	}

	/**
	 * Set value of Submitted
	 * @param context
	 * @param submitted
	 */
	public final void setSubmitted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String submitted)
	{
		getMendixObject().setValue(context, MemberNames.Submitted.toString(), submitted);
	}

	/**
	 * @return value of Approved
	 */
	public final java.lang.String getApproved()
	{
		return getApproved(getContext());
	}

	/**
	 * @param context
	 * @return value of Approved
	 */
	public final java.lang.String getApproved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Approved.toString());
	}

	/**
	 * Set value of Approved
	 * @param approved
	 */
	public final void setApproved(java.lang.String approved)
	{
		setApproved(getContext(), approved);
	}

	/**
	 * Set value of Approved
	 * @param context
	 * @param approved
	 */
	public final void setApproved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String approved)
	{
		getMendixObject().setValue(context, MemberNames.Approved.toString(), approved);
	}

	/**
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole()
	{
		return getUserRole(getContext());
	}

	/**
	 * @param context
	 * @return value of UserRole
	 */
	public final java.lang.String getUserRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserRole.toString());
	}

	/**
	 * Set value of UserRole
	 * @param userrole
	 */
	public final void setUserRole(java.lang.String userrole)
	{
		setUserRole(getContext(), userrole);
	}

	/**
	 * Set value of UserRole
	 * @param context
	 * @param userrole
	 */
	public final void setUserRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userrole)
	{
		getMendixObject().setValue(context, MemberNames.UserRole.toString(), userrole);
	}

	/**
	 * Set value of UserType
	 * @param usertype
	 */
	public final expenses.proxies.UserType getUserType()
	{
		return getUserType(getContext());
	}

	/**
	 * @param context
	 * @return value of UserType
	 */
	public final expenses.proxies.UserType getUserType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.UserType.toString());
		if (obj == null)
			return null;

		return expenses.proxies.UserType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of UserType
	 * @param usertype
	 */
	public final void setUserType(expenses.proxies.UserType usertype)
	{
		setUserType(getContext(), usertype);
	}

	/**
	 * Set value of UserType
	 * @param context
	 * @param usertype
	 */
	public final void setUserType(com.mendix.systemwideinterfaces.core.IContext context, expenses.proxies.UserType usertype)
	{
		if (usertype != null)
			getMendixObject().setValue(context, MemberNames.UserType.toString(), usertype.toString());
		else
			getMendixObject().setValue(context, MemberNames.UserType.toString(), null);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final expenses.proxies.Employee that = (expenses.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Expenses.Employee";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
