// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expenses.proxies;

public class Expense extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Expenses.Expense";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Date("Date"),
		Description("Description"),
		Amount("Amount"),
		CurrencyAndAmount("CurrencyAndAmount"),
		Status("Status"),
		StatusMessage("StatusMessage"),
		RejectionReason("RejectionReason"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		GeoLocated("GeoLocated"),
		ReceiptAdded("ReceiptAdded"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Expense_ExpenseType("Expenses.Expense_ExpenseType"),
		Expense_Employee("Expenses.Expense_Employee");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Expense(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Expenses.Expense"));
	}

	protected Expense(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject expenseMendixObject)
	{
		super(context, expenseMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Expenses.Expense", expenseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Expenses.Expense");
	}

	/**
	 * @deprecated Use 'Expense.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static expenses.proxies.Expense initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return expenses.proxies.Expense.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static expenses.proxies.Expense initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new expenses.proxies.Expense(context, mendixObject);
	}

	public static expenses.proxies.Expense load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return expenses.proxies.Expense.initialize(context, mendixObject);
	}

	public static java.util.List<expenses.proxies.Expense> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<expenses.proxies.Expense> result = new java.util.ArrayList<expenses.proxies.Expense>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Expenses.Expense" + xpathConstraint))
			result.add(expenses.proxies.Expense.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount()
	{
		return getAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of Amount
	 */
	public final java.math.BigDecimal getAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Amount.toString());
	}

	/**
	 * Set value of Amount
	 * @param amount
	 */
	public final void setAmount(java.math.BigDecimal amount)
	{
		setAmount(getContext(), amount);
	}

	/**
	 * Set value of Amount
	 * @param context
	 * @param amount
	 */
	public final void setAmount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amount)
	{
		getMendixObject().setValue(context, MemberNames.Amount.toString(), amount);
	}

	/**
	 * @return value of CurrencyAndAmount
	 */
	public final java.lang.String getCurrencyAndAmount()
	{
		return getCurrencyAndAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrencyAndAmount
	 */
	public final java.lang.String getCurrencyAndAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrencyAndAmount.toString());
	}

	/**
	 * Set value of CurrencyAndAmount
	 * @param currencyandamount
	 */
	public final void setCurrencyAndAmount(java.lang.String currencyandamount)
	{
		setCurrencyAndAmount(getContext(), currencyandamount);
	}

	/**
	 * Set value of CurrencyAndAmount
	 * @param context
	 * @param currencyandamount
	 */
	public final void setCurrencyAndAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currencyandamount)
	{
		getMendixObject().setValue(context, MemberNames.CurrencyAndAmount.toString(), currencyandamount);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final expenses.proxies.Expense_Status getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final expenses.proxies.Expense_Status getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return expenses.proxies.Expense_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(expenses.proxies.Expense_Status status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, expenses.proxies.Expense_Status status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return value of StatusMessage
	 */
	public final java.lang.String getStatusMessage()
	{
		return getStatusMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusMessage
	 */
	public final java.lang.String getStatusMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StatusMessage.toString());
	}

	/**
	 * Set value of StatusMessage
	 * @param statusmessage
	 */
	public final void setStatusMessage(java.lang.String statusmessage)
	{
		setStatusMessage(getContext(), statusmessage);
	}

	/**
	 * Set value of StatusMessage
	 * @param context
	 * @param statusmessage
	 */
	public final void setStatusMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statusmessage)
	{
		getMendixObject().setValue(context, MemberNames.StatusMessage.toString(), statusmessage);
	}

	/**
	 * @return value of RejectionReason
	 */
	public final java.lang.String getRejectionReason()
	{
		return getRejectionReason(getContext());
	}

	/**
	 * @param context
	 * @return value of RejectionReason
	 */
	public final java.lang.String getRejectionReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RejectionReason.toString());
	}

	/**
	 * Set value of RejectionReason
	 * @param rejectionreason
	 */
	public final void setRejectionReason(java.lang.String rejectionreason)
	{
		setRejectionReason(getContext(), rejectionreason);
	}

	/**
	 * Set value of RejectionReason
	 * @param context
	 * @param rejectionreason
	 */
	public final void setRejectionReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rejectionreason)
	{
		getMendixObject().setValue(context, MemberNames.RejectionReason.toString(), rejectionreason);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.lang.Double getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.lang.Double getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.lang.Double latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.lang.Double getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.lang.Double getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.lang.Double longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of GeoLocated
	 */
	public final java.lang.Boolean getGeoLocated()
	{
		return getGeoLocated(getContext());
	}

	/**
	 * @param context
	 * @return value of GeoLocated
	 */
	public final java.lang.Boolean getGeoLocated(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.GeoLocated.toString());
	}

	/**
	 * Set value of GeoLocated
	 * @param geolocated
	 */
	public final void setGeoLocated(java.lang.Boolean geolocated)
	{
		setGeoLocated(getContext(), geolocated);
	}

	/**
	 * Set value of GeoLocated
	 * @param context
	 * @param geolocated
	 */
	public final void setGeoLocated(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean geolocated)
	{
		getMendixObject().setValue(context, MemberNames.GeoLocated.toString(), geolocated);
	}

	/**
	 * @return value of ReceiptAdded
	 */
	public final java.lang.Boolean getReceiptAdded()
	{
		return getReceiptAdded(getContext());
	}

	/**
	 * @param context
	 * @return value of ReceiptAdded
	 */
	public final java.lang.Boolean getReceiptAdded(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ReceiptAdded.toString());
	}

	/**
	 * Set value of ReceiptAdded
	 * @param receiptadded
	 */
	public final void setReceiptAdded(java.lang.Boolean receiptadded)
	{
		setReceiptAdded(getContext(), receiptadded);
	}

	/**
	 * Set value of ReceiptAdded
	 * @param context
	 * @param receiptadded
	 */
	public final void setReceiptAdded(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean receiptadded)
	{
		getMendixObject().setValue(context, MemberNames.ReceiptAdded.toString(), receiptadded);
	}

	/**
	 * @return value of Expense_ExpenseType
	 */
	public final expenses.proxies.ExpenseType getExpense_ExpenseType() throws com.mendix.core.CoreException
	{
		return getExpense_ExpenseType(getContext());
	}

	/**
	 * @param context
	 * @return value of Expense_ExpenseType
	 */
	public final expenses.proxies.ExpenseType getExpense_ExpenseType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		expenses.proxies.ExpenseType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Expense_ExpenseType.toString());
		if (identifier != null)
			result = expenses.proxies.ExpenseType.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Expense_ExpenseType
	 * @param expense_expensetype
	 */
	public final void setExpense_ExpenseType(expenses.proxies.ExpenseType expense_expensetype)
	{
		setExpense_ExpenseType(getContext(), expense_expensetype);
	}

	/**
	 * Set value of Expense_ExpenseType
	 * @param context
	 * @param expense_expensetype
	 */
	public final void setExpense_ExpenseType(com.mendix.systemwideinterfaces.core.IContext context, expenses.proxies.ExpenseType expense_expensetype)
	{
		if (expense_expensetype == null)
			getMendixObject().setValue(context, MemberNames.Expense_ExpenseType.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Expense_ExpenseType.toString(), expense_expensetype.getMendixObject().getId());
	}

	/**
	 * @return value of Expense_Employee
	 */
	public final expenses.proxies.Employee getExpense_Employee() throws com.mendix.core.CoreException
	{
		return getExpense_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Expense_Employee
	 */
	public final expenses.proxies.Employee getExpense_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		expenses.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Expense_Employee.toString());
		if (identifier != null)
			result = expenses.proxies.Employee.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Expense_Employee
	 * @param expense_employee
	 */
	public final void setExpense_Employee(expenses.proxies.Employee expense_employee)
	{
		setExpense_Employee(getContext(), expense_employee);
	}

	/**
	 * Set value of Expense_Employee
	 * @param context
	 * @param expense_employee
	 */
	public final void setExpense_Employee(com.mendix.systemwideinterfaces.core.IContext context, expenses.proxies.Employee expense_employee)
	{
		if (expense_employee == null)
			getMendixObject().setValue(context, MemberNames.Expense_Employee.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Expense_Employee.toString(), expense_employee.getMendixObject().getId());
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final expenses.proxies.Expense that = (expenses.proxies.Expense) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Expenses.Expense";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
